apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-go-server-deployment
  labels:
    app: simple-go-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-go-server
  template:
    metadata:
      labels:
        app: simple-go-server
    spec:
      containers:
      - name: simple-go-server
        image: victorismaelreeves/simple-go-server:v1.0
        ports:
        - containerPort: 9090
