- hosts: all
  tasks:
    - name: service template
      become: yes # sudo
      template:
        src: example.service.j2
        dest: /etc/systemd/system/example.service

    - name: copy artifact
      copy:
        src: example1
        dest: /home/vagrant/example1
        mode: '0777'

    - name: enable and start service
      become: yes # sudo
      systemd:
        name: example
        enabled: yes
        state: restarted
